name: Build and Deploy Snapshot
on:
  push:
    branches:
      - 1.4.x
permissions:
  actions: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-and-deploy-snapshot:
    name: Build and Deploy Snapshot
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'spring-projects/spring-graphql' }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Build and Publish
        id: build-and-publish
        uses: ./.github/actions/build-and-publish
        with:
          develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
          publish: true
      - name: Deploy
        uses: spring-io/artifactory-deploy-action@dc1913008c0599f0c4b1fdafb6ff3c502b3565ea # v0.0.2
        with:
          uri: 'https://repo.spring.io'
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          build-name: ${{ format('spring-graphql-{0}', github.ref_name)}}
          repository: 'libs-snapshot-local'
          folder: 'deployment-repository'
          signing-key: ${{ secrets.GPG_PRIVATE_KEY }}
          signing-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          artifact-properties: |
            /**/spring-graphql-docs-*.zip::zip.name=spring-graphql,zip.type=docs,zip.deployed=false
      - name: Send Notification
        uses: ./.github/actions/send-notification
        if: always()
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          status: ${{ job.status }}
          build-scan-url: ${{ steps.build-and-publish.outputs.build-scan-url }}
          run-name: ${{ format('{0} | Linux | Java 17', github.ref_name) }}
    outputs:
      version: ${{ steps.build-and-publish.outputs.version }}