name: CI
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  ci:
    name: '${{ matrix.os.name}} | Java ${{ matrix.java.version}}'
    runs-on: ${{ matrix.os.id }}
    if: ${{ github.repository == 'spring-projects/spring-graphql' }}
    strategy:
      matrix:
        os:
          - id: ubuntu-latest
            name: Linux
        java:
          - version: 21
            toolchain: true
          - version: 22
            toolchain: true
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Build
        id: build
        uses: ./.github/actions/build-and-publish
        with:
          java-version: ${{ matrix.java.version }}
          java-distribution: ${{ matrix.java.distribution || 'liberica' }}
          java-toolchain: ${{ matrix.java.toolchain }}
          develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
      - name: Send Notification
        uses: ./.github/actions/send-notification
        if: always()
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          status: ${{ job.status }}
          build-scan-url: ${{ steps.build.outputs.build-scan-url }}
          run-name: ${{ format('{0} | {1} | Java {2}', github.ref_name, matrix.os.name, matrix.java.version) }}