name: Delete Staged Release
on:
  workflow_dispatch:
    inputs:
      build-version:
        description: 'Version of the build to delete'
        required: true
jobs:
  delete-staged-release:
    name: Delete Staged Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@18e785fb220d332edbf01964f853ff0fcaa22220 # v4.4.2
        env:
          JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      - name: Delete Build
        run: jfrog rt delete --build spring-graphql-${{ github.event.inputs.build-version }}